# Generated by Django 3.2.9 on 2021-12-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
