# Generated by Django 3.2.9 on 2021-12-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0005_game_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rented',
        ),
        migrations.AddField(
            model_name='rent',
            name='rented',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
